### ISSUE TITLE
Bad grammar in the ALG website

### ISSUE THREAD

**Issue by samarth-ba** [arch-linux-gui/alg-releases#1]
I was on the ALG website to grab my ISO and install it, when I noticed, the site has bad grammar, which in turn, makes it look not legit. If the developers wouldn't mind, I would like to help with correcting these minor mistakes to make the site better.

**Comment by demonkilleralg** [comment]
Please feel free to do so. PRs are welcome.

**Comment by samarth-ba** [comment]
No problem. I'll work on it as well when I have free time.
