### ISSUE TITLE
Add a package on GNOME version

### ISSUE THREAD

**Issue by Diolinux** [arch-linux-gui/alg-releases#2]
Hey, first, let me say: Amazing work that you are doing, specially in the modified versions. :)

I've been testing the GNOME one, and a package addition will make the distro eve better.

The package is: gnome-software-packagekit-plugin

This plugin enables the GNOME Software to search for apps on Arch repos, making it perfectly functional. Since is a very little package and make such a big difference, it'll be nice to have it by default.

Soon we'll be reviewing the distro on our youtube channel.

All the best.

**Comment by demonkilleralg** [comment]
This package does seem to exist, [have a look](https://github.com/arch-linux-gui/arch-linux-gui-gnome/blob/master/packages.x86_64#L132).

I am away for some time so I am not able to test, can you confirm if it is there in the live iso?

**Comment by Diolinux** [comment]
Hi, maybe o add it in a recent build? Last week, i have to install it manually with a `pacman -S gnome-software-packagekit-plugin`
Then it works with a GNOME Software reload. Don't know how you feel about it, but enabling flatpak and flathub by default, even with no packages pre-installed would be awesome too. :)

**Comment by demonkilleralg** [comment]
I rebuild the ISO with the mentioned package. 
![20211113_231508.jpg](https://user-images.githubusercontent.com/55846983/141653782-08aa2054-d992-4761-989e-8573822be901.jpg)

Software center doesn't seem to work, and my workaround has failed to. It seems I need to revert back to the original appstream package. 

The pamac package you see above, was used as a workaround.
