### ISSUE TITLE
Add some packages on XFCE Edition

### ISSUE THREAD

**Issue by Heus-Sueh** [arch-linux-gui/alg-releases#6]
gnome-software is used in many distros like linux mint xfce and xubuntu, gnome-software-packagekit-plugin for the aur repo and user-admin for config the users and groups on system.

**Comment by demonkilleralg** [comment]
noted will add

**Comment by Heus-Sueh** [comment]
plus some packages: mugshot to set the user, change the name, add image to profile and etc, gufw to set up the firewall, gnome-disk-utility to format the discs, file-roller to extract compressed files, lightdm-gtk-greeter and lightdm-gtk-greeter-settings to config lightdm, and maybe the redshift to adjust color temperature

**Comment by Heus-Sueh** [comment]
adds ttf-arphic-uming, ttf-baekmuk and ttf-sazanami packages for fonts to display correctly

**Comment by demonkilleralg** [comment]
All CJK fonts are to be replaced by noto-fonts-cjk

**Comment by Heus-Sueh** [comment]
add gvfs-mtp and android-tools (for adb and fastboot commands)
![Screenshot_2022-06-23_16-19-52](https://user-images.githubusercontent.com/98482469/175380791-3f665493-a766-459f-98f1-02be0d57a943.png)
![Screenshot_2022-06-23_16-23-10](https://user-images.githubusercontent.com/98482469/175380793-aa32233d-e0c2-413d-87e9-f7a5c77e1a1c.png)

**Comment by Heus-Sueh** [comment]
adding these packages for GNOME Edition and Cinnamon Edition would be a good idea too

**Comment by kaktoforum** [comment]
> add gvfs-mtp and android-tools (for adb and fastboot commands)
Why I need thees packages on my if I'm not using Android? Or if I'm not connecting it to my PC?
IMHO, can be easily installed by user if required.
