### ISSUE TITLE
Add graphics drivers for NVIDIA/AMD, to avoid overheating

### ISSUE THREAD

**Issue by Bzucko** [arch-linux-gui/alg-releases#7]
ISSUE:
Without graphics driver plenty of modern graphics cards are running on full 3D frequencies even if the GPU usage is 0%. What is even worse, plenty of manufacturers set fan speed in bios to 0 rpm until GPU temperature reaches ~ 60°C.
Graphics cards "overheat" unnecessarily fast and idle power consumption is stupidly high.
---------
After adding drivers it would be possible e.g. set fan speed to 1000rpm in NVIDIA X server settings(or using nvidia-smi) and set min/max frequencies for 2D desktop to 300MHz using command "nvidia-smi -lgc 300,300", which is enough for desktop activities, watching 1080p videos, ...

Maybe notebook systems have better temperature/power management outside of operating system, but for desktop it is disaster.

**Comment by demonkilleralg** [comment]
nvidia drivers are available in themed edition
