### ISSUE TITLE
Key error after try sudo pacman -Syu

### ISSUE THREAD

**Issue by gapr1983** [arch-linux-gui/alg-releases#8]
Hello people,

I would like to report this issues. after install the distro i try to update by terminal using sudo pacman -Syu, but I get this error
![Screenshot_20220314_193615](https://user-images.githubusercontent.com/75249210/158343377-c6959b69-06ea-4181-b25c-950ec9d9c4bd.png)
 
I only try to add the community repositories and Portugal mirror to the list, but not joy. Also I notice that i can not find some apps by Discovery, but if i search by terminal i can find it... the discovery settings are blank... And I don't know if im wrong but when i see the etc configuration is not familiar to me...

![Screenshot_20220315_092727](https://user-images.githubusercontent.com/75249210/158347849-0a70b965-205a-4959-91ed-d79db38b1465.png)
![Screenshot_20220315_092758](https://user-images.githubusercontent.com/75249210/158347899-7a99c57f-0daa-4e2a-a11d-95910e3993fe.png)
![Screenshot_20220315_092824](https://user-images.githubusercontent.com/75249210/158347924-277b6d5a-71d1-459f-a164-9d6acc1cccd5.png)

My laptop is this HP 15-bw015np. i do a clean install, with efi, swap, /home and / by separate. Thanks for help me.

**Comment by gapr1983** [comment]
Now im getting this message on Discover
![Screenshot_20220315_130741](https://user-images.githubusercontent.com/75249210/158384677-7a091ea9-5e82-4549-97fd-3a3fc1aa0769.png)
im not abel to use the laptop, im going to use other distro in order to work, if someone know more information i will install this distro again.

**Comment by Piqlet** [comment]
Install archlinux-kerring:
```
sudo pacman -S archlinux-keyring
```

**Comment by demonkilleralg** [comment]
solved
